<?xml version="1.0"?>
<!DOCTYPE examples [
  <!ELEMENT examples (example*)>
  <!ELEMENT example (nl*,syn*,augsyn*,mrl*,mrl-parse?,parse*)>
  <!ELEMENT nl (#PCDATA)>
  <!ELEMENT syn (#PCDATA)>
  <!ELEMENT augsyn (#PCDATA)>
  <!ELEMENT mrl (#PCDATA)>
  <!ELEMENT mrl-parse (node*)>
  <!ELEMENT node (#PCDATA)>
  <!ELEMENT parse (#PCDATA)>
]>
<examples>

<example id="2">
<nl lang="en">
If the ball is in our half , then position player 5 at -LRB- 0 , 10 -RRB- , and set its ball attraction to -LRB- 0.75 , 0.4 -RRB-
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (PRP$ our) (NN half)))))) (, ,) (ADVP (RB then)) (VP (VP (VB position) (NP (NN player) (CD 5)) (PP (IN at) (NP (PRN (-LRB- -LRB-) (NP (CD 0)) (, ,) (NP (CD 10)) (-RRB- -RRB-))))) (, ,) (CC and) (VP (VB set) (NP (PRP$ its) (NN ball) (NN attraction)) (PP (TO to) (NP (PRN (-LRB- -LRB-) (NP (CD 0.75)) (, ,) (NP (CD 0.4)) (-RRB- -RRB-)))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] the ball-[Condition:2] is-[Condition:2] in our-[Team:4] half-[Region:3] , then-[Rule:1] position-[Action:8] player-[Player:6] 5-[Unum:7] at -LRB--[Point:11] 0-[Num:12] ,-[Point:11] 10-[Num:13] -RRB--[Point:11] , and set-[Point:10] its ball-[Point:10] attraction-[Point:10] to -LRB--[Point:14] 0.75-[Num:15] ,-[Point:14] 0.4-[Num:16] -RRB--[Point:14])
</augsyn>
<mrl lang="robocup-clang">
(definerule b15004 direc
        ((bpos (half our)) (do (player our {5}) (pos (pt-with-ball-attraction (pt 0 10) (pt 0.75 0.4))))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="3"> *n:Region -> ({ ( half *n:Team ) }) </node>
<node id="4"> *n:Team -> ({ our }) </node>
<node id="5"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="6"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="7"> *n:Unum -> ({ 5 }) </node>
<node id="8"> *n:Action -> ({ ( pos *n:Region ) }) </node>
<node id="9"> *n:Region -> ({ *n:Point }) </node>
<node id="10"> *n:Point -> ({ ( pt-with-ball-attraction *n:Point *n:Point ) }) </node>
<node id="11"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="12"> *n:Num -> ({ 0 }) </node>
<node id="13"> *n:Num -> ({ 10 }) </node>
<node id="14"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="15"> *n:Num -> ({ 0.75 }) </node>
<node id="16"> *n:Num -> ({ 0.4 }) </node>
</mrl-parse>
</example>

<example id="5">
<nl lang="en">
If the ball is in opponent 's half , then the default position of player 5 should be within 4 meters of -LRB- -13 , -18 -RRB- with ball attraction -LRB- 0.2 , 0.1 -RRB-
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (NP (NN opponent) (POS 's)) (NN half)))))) (, ,) (ADVP (RB then)) (NP (NP (DT the) (NN default) (NN position)) (PP (IN of) (NP (NN player) (CD 5)))) (VP (MD should) (VP (VB be) (PP (IN within) (NP (NP (CD 4) (NNS meters)) (PP (IN of) (NP (NP (PRN (-LRB- -LRB-) (NP (CD -13)) (, ,) (NP (CD -18)) (-RRB- -RRB-))) (PP (IN with) (NP (NN ball) (NN attraction) (PRN (-LRB- -LRB-) (NP (CD 0.2)) (, ,) (NP (CD 0.1)) (-RRB- -RRB-)))))))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] the ball-[Condition:2] is-[Condition:2] in opponent-[Team:4] 's-[Team:4] half-[Region:3] , then-[Rule:1] the default-[Action:8] position-[Action:8] of player-[Player:6] 5-[Unum:7] should-[Directive:5] be-[Action:8] within-[Region:9] 4-[Num:17] meters of-[Region:9] -LRB--[Point:11] -13-[Num:12] ,-[Point:11] -18-[Num:13] -RRB--[Point:11] with ball-[Point:10] attraction-[Point:10] -LRB--[Point:14] 0.2-[Num:15] ,-[Point:14] 0.1-[Num:16] -RRB--[Point:14])
</augsyn>
<mrl lang="robocup-clang">
(definerule FH35 direc
        ((bpos (half opp)) (do (player our {5}) (home (circle (pt-with-ball-attraction (pt -13.0 -18.0) (pt 0.2 0.1)) 4)))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="3"> *n:Region -> ({ ( half *n:Team ) }) </node>
<node id="4"> *n:Team -> ({ opp }) </node>
<node id="5"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="6"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="7"> *n:Unum -> ({ 5 }) </node>
<node id="8"> *n:Action -> ({ ( home *n:Region ) }) </node>
<node id="9"> *n:Region -> ({ ( circle *n:Point *n:Num ) }) </node>
<node id="10"> *n:Point -> ({ ( pt-with-ball-attraction *n:Point *n:Point ) }) </node>
<node id="11"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="12"> *n:Num -> ({ -13.0 }) </node>
<node id="13"> *n:Num -> ({ -18.0 }) </node>
<node id="14"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="15"> *n:Num -> ({ 0.2 }) </node>
<node id="16"> *n:Num -> ({ 0.1 }) </node>
<node id="17"> *n:Num -> ({ 4 }) </node>
</mrl-parse>
</example>

<example id="10">
<nl lang="en">
The default position of player 11 should always be -LRB- 15 , 15 -RRB-
</nl>
<syn lang="en">
(S (NP (NP (DT The) (NN default) (NN position)) (PP (IN of) (NP (NN player) (CD 11)))) (VP (MD should) (ADVP (RB always)) (VP (VB be) (NP (PRN (-LRB- -LRB-) (NP (CD 15)) (, ,) (NP (CD 15)) (-RRB- -RRB-))))))
</syn>
<augsyn lang="en">
(S The default-[Action:6] position-[Action:6] of player-[Player:4] 11-[Unum:5] should-[Directive:3] always-[Condition:2] be-[Action:6] -LRB--[Point:8] 15-[Num:9] ,-[Point:8] 15-[Num:10] -RRB--[Point:8])
</augsyn>
<mrl lang="robocup-clang">
(definerule Player11 direc
        ((true) (do (player our {11}) (home (pt 15 15)))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( true ) }) </node>
<node id="3"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="4"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="5"> *n:Unum -> ({ 11 }) </node>
<node id="6"> *n:Action -> ({ ( home *n:Region ) }) </node>
<node id="7"> *n:Region -> ({ *n:Point }) </node>
<node id="8"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="9"> *n:Num -> ({ 15 }) </node>
<node id="10"> *n:Num -> ({ 15 }) </node>
</mrl-parse>
</example>

<example id="12">
<nl lang="en">
If the ball is close to the far left corner when the play mode is play_on , then player 4 should pass the ball to opponent 's penalty area
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (ADJP (JJ close) (PP (TO to) (NP (DT the) (ADJP (RB far) (JJ left)) (NN corner))))) (SBAR (WHADVP (WRB when)) (S (NP (DT the) (NN play) (NN mode)) (VP (VBZ is) (NP (NN play_on))))))) (, ,) (ADVP (RB then)) (NP (NN player) (CD 4)) (VP (MD should) (VP (VB pass) (NP (DT the) (NN ball)) (PP (TO to) (NP (NP (NN opponent) (POS 's)) (NN penalty) (NN area))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] the ball-[Condition:4] is-[Condition:4] close to the far-[Team:7] left-[Region:5] corner-[Region:6] when-[Condition:2] the play-[Condition:3] mode-[Condition:3] is-[Condition:3] play_on-[Condition:3] , then-[Rule:1] player-[Player:9] 4-[Unum:10] should-[Directive:8] pass-[Action:11] the ball-[Action:11] to opponent-[Team:13] 's-[Team:13] penalty-[Region:12] area-[Region:12])
</augsyn>
<mrl lang="robocup-clang">
(definerule MDR10R6 direc
        ((and (playm play_on) (bpos (left-quarter (near-goal-line opp)))) (do (player our {4}) (pass (penalty-area opp)))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( and *n:Condition *n:Condition ) }) </node>
<node id="3"> *n:Condition -> ({ ( playm play_on ) }) </node>
<node id="4"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="5"> *n:Region -> ({ ( left-quarter *n:Region ) }) </node>
<node id="6"> *n:Region -> ({ ( near-goal-line *n:Team ) }) </node>
<node id="7"> *n:Team -> ({ opp }) </node>
<node id="8"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="9"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="10"> *n:Unum -> ({ 4 }) </node>
<node id="11"> *n:Action -> ({ ( pass *n:Region ) }) </node>
<node id="12"> *n:Region -> ({ ( penalty-area *n:Team ) }) </node>
<node id="13"> *n:Team -> ({ opp }) </node>
</mrl-parse>
</example>

<example id="14">
<nl lang="en">
If the ball is in -LSB- -LRB- -17.5 , -17 -RRB- , -LRB- 0 , 0 -RRB- -RSB-  , then all players except the goalie should pass the ball to the far left side of opponent 's midfield
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (PRN (-LRB- -LSB-) (PRN (-LRB- -LRB-) (NP (CD -17.5)) (, ,) (NP (CD -17)) (-RRB- -RRB-)) (, ,) (PRN (-LRB- -LRB-) (NP (CD 0)) (, ,) (NP (CD 0)) (-RRB- -RRB-)) (-RRB- -RSB-))))))) (, ,) (ADVP (RB then)) (NP (NP (DT all) (NNS players)) (PP (IN except) (NP (DT the) (NN goalie)))) (VP (MD should) (VP (VB pass) (NP (DT the) (NN ball)) (PP (TO to) (NP (NP (DT the) (ADJP (RB far) (JJ left)) (NN side)) (PP (IN of) (NP (NP (NN opponent) (POS 's)) (NN midfield))))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] the ball-[Condition:2] is-[Condition:2] in -LSB--[Region:3] -LRB--[Point:4] -17.5-[Num:5] ,-[Point:4] -17-[Num:6] -RRB--[Point:4] ,-[Region:3] -LRB--[Point:7] 0-[Num:8] ,-[Point:7] 0-[Num:9] -RRB--[Point:7] -RSB--[Region:3] , then-[Rule:1] all players-[Player:11] except-[Player:11] the goalie-[Unum:12] should-[Directive:10] pass-[Action:13] the ball-[Action:13] to the far-[Region:14] left-[Region:14] side-[Region:14] of opponent-[Team:16] 's-[Team:16] midfield-[Region:15])
</augsyn>
<mrl lang="robocup-clang">
(definerule b37 direc
        ((bpos (rec (pt -17.5 -17) (pt 0 0))) (do (player-except our {1}) (pass (left-quarter (midfield opp))))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="3"> *n:Region -> ({ ( rec *n:Point *n:Point ) }) </node>
<node id="4"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="5"> *n:Num -> ({ -17.5 }) </node>
<node id="6"> *n:Num -> ({ -17 }) </node>
<node id="7"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="8"> *n:Num -> ({ 0 }) </node>
<node id="9"> *n:Num -> ({ 0 }) </node>
<node id="10"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="11"> *n:Player -> ({ ( player-except our { *n:Unum } ) }) </node>
<node id="12"> *n:Unum -> ({ 1 }) </node>
<node id="13"> *n:Action -> ({ ( pass *n:Region ) }) </node>
<node id="14"> *n:Region -> ({ ( left-quarter *n:Region ) }) </node>
<node id="15"> *n:Region -> ({ ( midfield *n:Team ) }) </node>
<node id="16"> *n:Team -> ({ opp }) </node>
</mrl-parse>
</example>

<example id="15">
<nl lang="en">
When the ball is in RP1 , players 2 to 11 should pass the ball to RP2
</nl>
<syn lang="en">
(S (SBAR (WHADVP (WRB When)) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (NNP RP1)))))) (, ,) (NP (NP (NNS players)) (NP (QP (CD 2) (TO to) (CD 11)))) (VP (MD should) (VP (VB pass) (NP (DT the) (NN ball)) (PP (TO to) (NP (NNP RP2))))))
</syn>
<augsyn lang="en">
(S When-[Rule:1] the ball-[Condition:2] is-[Condition:2] in RP1-[Ident:4] , players-[Player:6] 2-[Unum:7] to-[Player:6] 11-[Unum:8] should-[Directive:5] pass-[Action:9] the ball-[Action:9] to RP2-[Ident:11])
</augsyn>
<mrl lang="robocup-clang">
(definerule b1 direc
        ((bpos "RP1") (do (player-range our 2 11) (pass "RP2"))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="3"> *n:Region -> ({ " *n:Ident " }) </node>
<node id="4"> *n:Ident -> ({ RP1 }) </node>
<node id="5"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="6"> *n:Player -> ({ ( player-range our *n:Unum *n:Unum ) }) </node>
<node id="7"> *n:Unum -> ({ 2 }) </node>
<node id="8"> *n:Unum -> ({ 11 }) </node>
<node id="9"> *n:Action -> ({ ( pass *n:Region ) }) </node>
<node id="10"> *n:Region -> ({ " *n:Ident " }) </node>
<node id="11"> *n:Ident -> ({ RP2 }) </node>
</mrl-parse>
</example>

<example id="17">
<nl lang="en">
If player 7 has the ball , then it should clear the ball from -LRB- 10 , -40 -RRB-
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (NN player) (CD 7)) (VP (VBZ has) (NP (DT the) (NN ball))))) (, ,) (ADVP (RB then)) (NP (PRP it)) (VP (MD should) (VP (VB clear) (NP (DT the) (NN ball)) (PP (IN from) (NP (PRN (-LRB- -LRB-) (NP (CD 10)) (, ,) (NP (CD -40)) (-RRB- -RRB-)))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] player-[Player:3] 7-[Unum:4] has-[Condition:2] the ball-[Condition:2] , then-[Rule:1] it-[Player:6] should-[Directive:5] clear-[Action:7] the ball-[Action:7] from -LRB--[Point:9] 10-[Num:10] ,-[Point:9] -40-[Num:11] -RRB--[Point:9])
</augsyn>
<mrl lang="robocup-clang">
(definerule utdefclr3 direc
        ((bowner (player our {7})) (do (player our {7}) (clear (pt 10 -40)))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bowner *n:Player ) }) </node>
<node id="3"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="4"> *n:Unum -> ({ 7 }) </node>
<node id="5"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="6"> *n:Player -> ({ *^:Player }) </node>
<node id="7"> *n:Action -> ({ ( clear *n:Region ) }) </node>
<node id="8"> *n:Region -> ({ *n:Point }) </node>
<node id="9"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="10"> *n:Num -> ({ 10 }) </node>
<node id="11"> *n:Num -> ({ -40 }) </node>
</mrl-parse>
</example>

<example id="19">
<nl lang="en">
Call the condition where players 10 and 11 are not the ball owner to be COND9
</nl>
<syn lang="en">
(S (VP (VB Call) (S (NP (NP (DT the) (NN condition)) (SBAR (WHADVP (WRB where)) (S (NP (NNS players) (QP (CD 10) (CC and) (CD 11))) (VP (VBP are) (RB not) (NP (DT the) (NN ball) (NN owner)))))) (VP (TO to) (VP (VB be) (NP (NNP COND9)))))))
</syn>
<augsyn lang="en">
(S Call-[Statement:0] the condition-[Statement:0] where players-[Player:4] 10-[Unum:5] and-[Player:4] 11-[Unum:6] are-[Condition:3] not-[Condition:2] the ball-[Condition:3] owner-[Condition:3] to be-[Statement:0] COND9-[Ident:1])
</augsyn>
<mrl lang="robocup-clang">
(definec "COND9"
          (not (bowner (player our {10 11}))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ ( definec " *n:Ident " *n:Condition ) }) </node>
<node id="1"> *n:Ident -> ({ COND9 }) </node>
<node id="2"> *n:Condition -> ({ ( not *n:Condition ) }) </node>
<node id="3"> *n:Condition -> ({ ( bowner *n:Player ) }) </node>
<node id="4"> *n:Player -> ({ ( player our { *n:Unum *n:Unum } ) }) </node>
<node id="5"> *n:Unum -> ({ 10 }) </node>
<node id="6"> *n:Unum -> ({ 11 }) </node>
</mrl-parse>
</example>

<example id="20">
<nl lang="en">
If the ball is in our half , then position player 5 at -LRB- 0 , 10 -RRB- and set its ball attraction to -LRB- 0.75 , 0.4 -RRB-
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (PRP$ our) (NN half)))))) (, ,) (ADVP (RB then)) (VP (VP (VB position) (NP (NN player) (CD 5)) (PP (IN at) (NP (PRN (-LRB- -LRB-) (NP (CD 0)) (, ,) (NP (CD 10)) (-RRB- -RRB-))))) (CC and) (VP (VB set) (NP (PRP$ its) (NN ball) (NN attraction)) (PP (TO to) (NP (PRN (-LRB- -LRB-) (NP (CD 0.75)) (, ,) (NP (CD 0.4)) (-RRB- -RRB-)))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] the ball-[Condition:2] is-[Condition:2] in our-[Team:4] half-[Region:3] , then-[Rule:1] position-[Action:8] player-[Player:6] 5-[Unum:7] at -LRB--[Point:11] 0-[Num:12] ,-[Point:11] 10-[Num:13] -RRB--[Point:11] and set-[Point:10] its ball-[Point:10] attraction-[Point:10] to -LRB--[Point:14] 0.75-[Num:15] ,-[Point:14] 0.4-[Num:16] -RRB--[Point:14])
</augsyn>
<mrl lang="robocup-clang">
(definerule b15015 direc
        ((bpos (half our)) (do (player our {5}) (pos (pt-with-ball-attraction (pt 0 10) (pt 0.75 0.4))))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="3"> *n:Region -> ({ ( half *n:Team ) }) </node>
<node id="4"> *n:Team -> ({ our }) </node>
<node id="5"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="6"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="7"> *n:Unum -> ({ 5 }) </node>
<node id="8"> *n:Action -> ({ ( pos *n:Region ) }) </node>
<node id="9"> *n:Region -> ({ *n:Point }) </node>
<node id="10"> *n:Point -> ({ ( pt-with-ball-attraction *n:Point *n:Point ) }) </node>
<node id="11"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="12"> *n:Num -> ({ 0 }) </node>
<node id="13"> *n:Num -> ({ 10 }) </node>
<node id="14"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="15"> *n:Num -> ({ 0.75 }) </node>
<node id="16"> *n:Num -> ({ 0.4 }) </node>
</mrl-parse>
</example>

<example id="23">
<nl lang="en">
If the ball is in -LSB- -LRB- 0 , -17 -RRB- , -LRB- 17.5 , 0 -RRB- -RSB- , then all players except the goalie should pass the ball to -LSB- -LRB- 17.5 , 0 -RRB- , -LRB- 35 , 17 -RRB- -RSB-
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (PRN (-LRB- -LSB-) (PRN (-LRB- -LRB-) (NP (CD 0)) (, ,) (NP (CD -17)) (-RRB- -RRB-)) (, ,) (PRN (-LRB- -LRB-) (NP (CD 17.5)) (, ,) (NP (CD 0)) (-RRB- -RRB-)) (-RRB- -RSB-))))))) (, ,) (ADVP (RB then)) (NP (NP (DT all) (NNS players)) (PP (IN except) (NP (DT the) (NN goalie)))) (VP (MD should) (VP (VB pass) (NP (DT the) (NN ball)) (PP (TO to) (NP (PRN (-LRB- -LSB-) (PRN (-LRB- -LRB-) (NP (CD 17.5)) (, ,) (NP (CD 0)) (-RRB- -RRB-)) (, ,) (PRN (-LRB- -LRB-) (NP (CD 35)) (, ,) (NP (CD 17)) (-RRB- -RRB-)) (-RRB- -RSB-)))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] the ball-[Condition:2] is-[Condition:2] in -LSB--[Region:3] -LRB--[Point:4] 0-[Num:5] ,-[Point:4] -17-[Num:6] -RRB--[Point:4] ,-[Region:3] -LRB--[Point:7] 17.5-[Num:8] ,-[Point:7] 0-[Num:9] -RRB--[Point:7] -RSB--[Region:3] , then-[Rule:1] all players-[Player:11] except-[Player:11] the goalie-[Unum:12] should-[Directive:10] pass-[Action:13] the ball-[Action:13] to -LSB--[Region:14] -LRB--[Point:15] 17.5-[Num:16] ,-[Point:15] 0-[Num:17] -RRB--[Point:15] ,-[Region:14] -LRB--[Point:18] 35-[Num:19] ,-[Point:18] 17-[Num:20] -RRB--[Point:18] -RSB--[Region:14])
</augsyn>
<mrl lang="robocup-clang">
(definerule b39 direc
        ((bpos (rec (pt 0 -17) (pt 17.5 0))) (do (player-except our {1}) (pass (rec (pt 17.5 0) (pt 35 17))))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="3"> *n:Region -> ({ ( rec *n:Point *n:Point ) }) </node>
<node id="4"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="5"> *n:Num -> ({ 0 }) </node>
<node id="6"> *n:Num -> ({ -17 }) </node>
<node id="7"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="8"> *n:Num -> ({ 17.5 }) </node>
<node id="9"> *n:Num -> ({ 0 }) </node>
<node id="10"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="11"> *n:Player -> ({ ( player-except our { *n:Unum } ) }) </node>
<node id="12"> *n:Unum -> ({ 1 }) </node>
<node id="13"> *n:Action -> ({ ( pass *n:Region ) }) </node>
<node id="14"> *n:Region -> ({ ( rec *n:Point *n:Point ) }) </node>
<node id="15"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="16"> *n:Num -> ({ 17.5 }) </node>
<node id="17"> *n:Num -> ({ 0 }) </node>
<node id="18"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="19"> *n:Num -> ({ 35 }) </node>
<node id="20"> *n:Num -> ({ 17 }) </node>
</mrl-parse>
</example>

<example id="24">
<nl lang="en">
Player 3 should not intercept the ball if the ball is within 32 meters of our goal line and not in our left penalty area
</nl>
<syn lang="en">
(S (NP (NN Player) (CD 3)) (VP (MD should) (RB not) (VP (VB intercept) (NP (DT the) (NN ball)))) (SBAR (IN if) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (PP (IN within) (NP (NP (CD 32) (NNS meters)) (PP (IN of) (NP (PRP$ our) (NN goal) (NN line))))) (CC and) (PP (RB not) (IN in) (NP (PRP$ our) (JJ left) (NN penalty) (NN area))))))))
</syn>
<augsyn lang="en">
(S Player-[Player:14] 3-[Unum:15] should-[Directive:13] not-[Directive:13] intercept-[Action:16] the ball-[Action:16] if-[Rule:1] the ball-[Condition:3] is-[Condition:3] within-[Region:4] 32-[Num:7] meters of-[Region:4] our-[Team:5] goal-[Region:4] line-[Region:4] and-[Condition:2] not-[Condition:8] in-[Condition:9] our-[Team:12] left-[Region:10] penalty-[Region:11] area-[Region:11])
</augsyn>
<mrl lang="robocup-clang">
(definerule b21001 direc
        ((and (bpos (from-goal-line our 0 32)) (not (bpos (left (penalty-area our))))) (dont (player our {3}) (intercept))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( and *n:Condition *n:Condition ) }) </node>
<node id="3"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="4"> *n:Region -> ({ ( from-goal-line *n:Team *n:Num *n:Num ) }) </node>
<node id="5"> *n:Team -> ({ our }) </node>
<node id="6"> *n:Num -> ({ 0 }) </node>
<node id="7"> *n:Num -> ({ 32 }) </node>
<node id="8"> *n:Condition -> ({ ( not *n:Condition ) }) </node>
<node id="9"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="10"> *n:Region -> ({ ( left *n:Region ) }) </node>
<node id="11"> *n:Region -> ({ ( penalty-area *n:Team ) }) </node>
<node id="12"> *n:Team -> ({ our }) </node>
<node id="13"> *n:Directive -> ({ ( dont *n:Player *n:Action ) }) </node>
<node id="14"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="15"> *n:Unum -> ({ 3 }) </node>
<node id="16"> *n:Action -> ({ ( intercept ) }) </node>
</mrl-parse>
</example>

<example id="27">
<nl lang="en">
Before kick - off , the default position of goalie should be directly in front of our goal
</nl>
<syn lang="en">
(S (PP (IN Before) (NP (NN kick) (: -) (NN off))) (, ,) (NP (NP (DT the) (NN default) (NN position)) (PP (IN of) (NP (NN goalie)))) (VP (MD should) (VP (VB be) (ADVP (RB directly)) (PP (IN in) (NP (NP (NN front)) (PP (IN of) (NP (PRP$ our) (NN goal))))))))
</syn>
<augsyn lang="en">
(S Before-[Condition:2] kick-[Condition:2] - off-[Condition:2] , the default-[Action:9] position-[Action:9] of goalie-[Player:7] should-[Directive:6] be-[Action:9] directly in front-[Point:11] of our-[Team:12] goal-[Point:11])
</augsyn>
<mrl lang="robocup-clang">
(definerule Formation_BK_1 direc
        ((or (playm bko) (playm ag_our) (playm ag_opp)) (do (player our {1}) (home (front-of-goal our)))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( or *n:Condition *n:Condition *n:Condition ) }) </node>
<node id="3"> *n:Condition -> ({ ( playm bko ) }) </node>
<node id="4"> *n:Condition -> ({ ( playm ag_our ) }) </node>
<node id="5"> *n:Condition -> ({ ( playm ag_opp ) }) </node>
<node id="6"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="7"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="8"> *n:Unum -> ({ 1 }) </node>
<node id="9"> *n:Action -> ({ ( home *n:Region ) }) </node>
<node id="10"> *n:Region -> ({ *n:Point }) </node>
<node id="11"> *n:Point -> ({ ( front-of-goal *n:Team ) }) </node>
<node id="12"> *n:Team -> ({ our }) </node>
</mrl-parse>
</example>

<example id="28">
<nl lang="en">
Let COND15 be true
</nl>
<syn lang="en">
(S (VP (VB Let) (S (NP (NNP COND15)) (VP (VB be) (ADJP (JJ true))))))
</syn>
<augsyn lang="en">
(S Let-[Statement:0] COND15-[Ident:1] be-[Statement:0] true-[Condition:2])
</augsyn>
<mrl lang="robocup-clang">
(definec "COND15" (true))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ ( definec " *n:Ident " *n:Condition ) }) </node>
<node id="1"> *n:Ident -> ({ COND15 }) </node>
<node id="2"> *n:Condition -> ({ ( true ) }) </node>
</mrl-parse>
</example>

<example id="30">
<nl lang="en">
If it is our goalie catch , then position player 4 at -LRB- -7 , 8 -RRB- with ball attraction -LRB- 0.3 , 0.2 -RRB-
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (PRP it)) (VP (VBZ is) (NP (PRP$ our) (NN goalie) (NN catch))))) (, ,) (ADVP (RB then)) (VP (VB position) (NP (NN player) (CD 4)) (PP (IN at) (NP (NP (PRN (-LRB- -LRB-) (NP (CD -7)) (, ,) (NP (CD 8)) (-RRB- -RRB-))) (PP (IN with) (NP (NN ball) (NN attraction) (PRN (-LRB- -LRB-) (NP (CD 0.3)) (, ,) (NP (CD 0.2)) (-RRB- -RRB-))))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] it-[Condition:2] is-[Condition:2] our-[Condition:2] goalie-[Condition:2] catch-[Condition:2] , then-[Rule:1] position-[Action:6] player-[Player:4] 4-[Unum:5] at -LRB--[Point:9] -7-[Num:10] ,-[Point:9] 8-[Num:11] -RRB--[Point:9] with ball-[Point:8] attraction-[Point:8] -LRB--[Point:12] 0.3-[Num:13] ,-[Point:12] 0.2-[Num:14] -RRB--[Point:12])
</augsyn>
<mrl lang="robocup-clang">
(definerule GCO4 direc
        ((playm gc_our) (do (player our {4}) (pos (pt-with-ball-attraction (pt -7.0 8.0) (pt 0.3 0.2))))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( playm gc_our ) }) </node>
<node id="3"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="4"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="5"> *n:Unum -> ({ 4 }) </node>
<node id="6"> *n:Action -> ({ ( pos *n:Region ) }) </node>
<node id="7"> *n:Region -> ({ *n:Point }) </node>
<node id="8"> *n:Point -> ({ ( pt-with-ball-attraction *n:Point *n:Point ) }) </node>
<node id="9"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="10"> *n:Num -> ({ -7.0 }) </node>
<node id="11"> *n:Num -> ({ 8.0 }) </node>
<node id="12"> *n:Point -> ({ ( pt *n:Num *n:Num ) }) </node>
<node id="13"> *n:Num -> ({ 0.3 }) </node>
<node id="14"> *n:Num -> ({ 0.2 }) </node>
</mrl-parse>
</example>

<example id="33">
<nl lang="en">
If the ball is in RP8 , then all players except the goalie should pass the ball to RP15
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (NNP RP8)))))) (, ,) (ADVP (RB then)) (NP (NP (DT all) (NNS players)) (PP (IN except) (NP (DT the) (NN goalie)))) (VP (MD should) (VP (VB pass) (NP (DT the) (NN ball)) (PP (TO to) (NP (NNP RP15))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] the ball-[Condition:2] is-[Condition:2] in RP8-[Ident:4] , then-[Rule:1] all players-[Player:6] except-[Player:6] the goalie-[Unum:7] should-[Directive:5] pass-[Action:8] the ball-[Action:8] to RP15-[Ident:10])
</augsyn>
<mrl lang="robocup-clang">
(definerule b12 direc
        ((bpos "RP8") (do (player-except our {1}) (pass "RP15"))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="3"> *n:Region -> ({ " *n:Ident " }) </node>
<node id="4"> *n:Ident -> ({ RP8 }) </node>
<node id="5"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="6"> *n:Player -> ({ ( player-except our { *n:Unum } ) }) </node>
<node id="7"> *n:Unum -> ({ 1 }) </node>
<node id="8"> *n:Action -> ({ ( pass *n:Region ) }) </node>
<node id="9"> *n:Region -> ({ " *n:Ident " }) </node>
<node id="10"> *n:Ident -> ({ RP15 }) </node>
</mrl-parse>
</example>

<example id="36">
<nl lang="en">
If the ball is in our half , then position player 1 directly in front of our goal
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (PRP$ our) (NN half)))))) (, ,) (ADVP (RB then)) (VP (VB position) (NP (NN player) (CD 1)) (PP (ADVP (RB directly)) (IN in) (NP (NP (NN front)) (PP (IN of) (NP (PRP$ our) (NN goal)))))))
</syn>
<augsyn lang="en">
(S If-[Rule:1] the ball-[Condition:2] is-[Condition:2] in our-[Team:4] half-[Region:3] , then-[Rule:1] position-[Action:8] player-[Player:6] 1-[Unum:7] directly in front-[Point:10] of our-[Team:11] goal-[Point:10])
</augsyn>
<mrl lang="robocup-clang">
(definerule b15011 direc
        ((bpos (half our)) (do (player our {1}) (pos (front-of-goal our)))))
</mrl>
<mrl-parse>
<node id="0"> *n:Statement -> ({ *n:Rule }) </node>
<node id="1"> *n:Rule -> ({ ( *n:Condition *n:Directive ) }) </node>
<node id="2"> *n:Condition -> ({ ( bpos *n:Region ) }) </node>
<node id="3"> *n:Region -> ({ ( half *n:Team ) }) </node>
<node id="4"> *n:Team -> ({ our }) </node>
<node id="5"> *n:Directive -> ({ ( do *n:Player *n:Action ) }) </node>
<node id="6"> *n:Player -> ({ ( player our { *n:Unum } ) }) </node>
<node id="7"> *n:Unum -> ({ 1 }) </node>
<node id="8"> *n:Action -> ({ ( pos *n:Region ) }) </node>
<node id="9"> *n:Region -> ({ *n:Point }) </node>
<node id="10"> *n:Point -> ({ ( front-of-goal *n:Team ) }) </node>
<node id="11"> *n:Team -> ({ our }) </node>
</mrl-parse>
</example>

<example id="38">
<nl lang="en">
If the ball is in opponent 's goal area , then the one who owns the ball should shoot it
</nl>
<syn lang="en">
(S (SBAR (IN If) (S (NP (DT the) (NN ball)) (VP (VBZ is) (PP (IN in) (NP (NP (NN opponent) (POS 's)) (NN goal) (NN area)))))) (, ,) (ADVP (RB then)) (NP (NP (DT the) (NN one)) (SBAR (WHNP (WP who)) (S (VP (VBZ owns) (NP (DT the) (NN ball)))))) (VP (MD should) (VP (VB shoot) (NP (PRP it)))))
</syn>
<augsyn lang="en">